USE [EczaneTakip]
GO

/****** Object:  Database [Eczane2]    Script Date: 08.01.2013 15:18:05 ******/
CREATE DATABASE [Eczane2] ON  PRIMARY 
( NAME = N'Eczane2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\Eczane2.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Eczane2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\Eczane2_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Eczane2] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EczaneTakip].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Eczane2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Eczane2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Eczane2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Eczane2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Eczane2] SET ARITHABORT OFF 
GO

ALTER DATABASE [Eczane2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Eczane2] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Eczane2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Eczane2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Eczane2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Eczane2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Eczane2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Eczane2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Eczane2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Eczane2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Eczane2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Eczane2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Eczane2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Eczane2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Eczane2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Eczane2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Eczane2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Eczane2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Eczane2] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Eczane2] SET  MULTI_USER 
GO

ALTER DATABASE [Eczane2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Eczane2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Eczane2] SET  READ_WRITE 
GO

